#!/usr/bin/env ruby
# Console for testing. TODO replace me with a proper cli.

require './lib/carbonmu.rb'
require 'awesome_print'
require 'pry'

CarbonMU::Server.initialize_database
Pry.start CarbonMU
